# Generated by Django 5.2.10 on 2026-01-21 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=300)),
                ('fecha_nacimiento', models.DateField()),
                ('biografia', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('nueva', 'Nueva'), ('usada', 'Usada'), ('deteriorada', 'Deteriorada'), ('retirar', 'A retirar')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=13, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('editorial', models.CharField(max_length=200)),
                ('fecha_publicacion', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('libro', 'Libro'), ('articulo', 'Articulo')], max_length=20)),
                ('autor', models.ManyToManyField(related_name='publicaciones', to='publicaciones.autor')),
                ('unidad', models.ManyToManyField(related_name='publicaciones', to='publicaciones.unidad')),
            ],
        ),
    ]
