# Generated by Django 5.2.10 on 2026-01-21 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publicaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='autor',
            name='biografia',
        ),
    ]
